/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

var fib = function(n) {
    if (n <= 1)
        return n;
    else
        return fib(n-1) + fib(n-2);
};

// returns nth value to reach goal, 55 in this case.
var n = 0;
var x = 0;
while (fib(n) <= 55) {
    n++;
};